
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * player
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function player(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'player', aFrame == undefined || aFrame == null? 'player0000' : aFrame);
	this.scale.set(0.7, 0.7);
	this.anchor.set(0.5, 0.5);
	var _anim_run = this.animations.add('run', ['player0000', 'player0001', 'player0002', 'player0003', 'player0004', 'player0005', 'player0006', 'player0007', 'player0008', 'player0009', 'player0010', 'player0011', 'player0012', 'player0013', 'player0014', 'player0015', 'player0016', 'player0017', 'player0018', 'player0019', 'player0020', 'player0021'], 40, true);
	_anim_run.play();
	this.game.physics.arcade.enable(this);
	this.body.velocity.x = 150.0;
	this.body.gravity.y = 1200.0;
	
}

/** @type Phaser.Sprite */
var player_proto = Object.create(Phaser.Sprite.prototype);
player.prototype = player_proto;
player.prototype.constructor = player;

/* --- end generated code --- */
// -- user code here --
