
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * redShip
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function redShip(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'ship', aFrame == undefined || aFrame == null? 'redShip0000' : aFrame);
	this.anchor.set(0.5, 0.5);
	var _anim_idle = this.animations.add('idle', ['redShip0000', 'redShip0001', 'redShip0002', 'redShip0003', 'redShip0004', 'redShip0005', 'redShip0006', 'redShip0007', 'redShip0008', 'redShip0009', 'redShip0010', 'redShip0011', 'redShip0012', 'redShip0013', 'redShip0014', 'redShip0015', 'redShip0016', 'redShip0017', 'redShip0018', 'redShip0019'], 30, true);
	_anim_idle.play();
	
}

/** @type Phaser.Sprite */
var redShip_proto = Object.create(Phaser.Sprite.prototype);
redShip.prototype = redShip_proto;
redShip.prototype.constructor = redShip;

/* --- end generated code --- */
// -- user code here --
