
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * wisherEnemy
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function wisherEnemy(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'wisherEnemy', aFrame == undefined || aFrame == null? 'BirdEnemy0000' : aFrame);
	this.scale.set(0.7, 0.7);
	this.anchor.set(0.5, 0.5);
	var _anim_fly = this.animations.add('fly', ['BirdEnemy0000', 'BirdEnemy0001', 'BirdEnemy0002', 'BirdEnemy0003', 'BirdEnemy0004', 'BirdEnemy0005', 'BirdEnemy0006', 'BirdEnemy0007', 'BirdEnemy0008'], 30, true);
	this.animations.add('kicked', ['BirdEnemyKicked0000'], 1, false);
	_anim_fly.play();
	this.game.physics.arcade.enable(this);
	this.body.setCircle(51.5);
	this.body.immovable = true;
	
	this.myCreate();
	
}

/** @type Phaser.Sprite */
var wisherEnemy_proto = Object.create(Phaser.Sprite.prototype);
wisherEnemy.prototype = wisherEnemy_proto;
wisherEnemy.prototype.constructor = wisherEnemy;

/* --- end generated code --- */
// -- user code here --
wisherEnemy.prototype.myCreate = function() {
	
	this.MyY = this.y + 30;
	this.tweenBtn = this.game.add.tween(this).to( {y:this.MyY}, 200, Phaser.Easing.Sinusoidal.InOut, true);
	this.tween2Btn = this.game.add.tween(this).to(  {y:this.y}, 200, Phaser.Easing.Sinusoidal.InOut, true);
	
	this.tweenBtn.chain(this.tween2Btn);
	this.tween2Btn.chain(this.tweenBtn);
	this.tweenBtn.start();
	this.body.velocity.x =   Math.random()  * (500 - 300) - 300;
	
};

wisherEnemy.prototype.update = function() {
	
	if(this.x<=-100){
		this.destroy();
	}
	if(this.x>=2200){
		this.destroy();
	}
};