
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.4 (Phaser v2.6.2)


/**
 * zepellin
 * @param {Phaser.Game} aGame A reference to the currently running game.
 * @param {Number} aX The x coordinate (in world space) to position the Sprite at.
 * @param {Number} aY The y coordinate (in world space) to position the Sprite at.
 * @param {any} aKey This is the image or texture used by the Sprite during rendering. It can be a string which is a reference to the Cache entry, or an instance of a RenderTexture or PIXI.Texture.
 * @param {any} aFrame If this Sprite is using part of a sprite sheet or texture atlas you can specify the exact frame to use by giving a string or numeric index.
 */
function zepellin(aGame, aX, aY, aKey, aFrame) {
	Phaser.Sprite.call(this, aGame, aX, aY, aKey || 'zepellin', aFrame == undefined || aFrame == null? 'zepellin0000' : aFrame);
	var _anim_showAds = this.animations.add('showAds', ['zepellin0000', 'zepellin0001', 'zepellin0002', 'zepellin0003', 'zepellin0004', 'zepellin0005', 'zepellin0006', 'zepellin0007', 'zepellin0008', 'zepellin0009', 'zepellin0010', 'zepellin0011', 'zepellin0012', 'zepellin0013', 'zepellin0014', 'zepellin0015', 'zepellin0016', 'zepellin0017', 'zepellin0018', 'zepellin0019', 'zepellin0020', 'zepellin0021', 'zepellin0022', 'zepellin0023', 'zepellin0024'], 20, true);
	_anim_showAds.play();
	
}

/** @type Phaser.Sprite */
var zepellin_proto = Object.create(Phaser.Sprite.prototype);
zepellin.prototype = zepellin_proto;
zepellin.prototype.constructor = zepellin;

/* --- end generated code --- */
// -- user code here --
zepellin.prototype.update = function() {

	this.x--;
	
	if(this.x<=-600){
		this.x = this.game.width+600;
	}
	};